name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/automudae/${{ github.event.release.tag_name }}

    steps:
      - name: Download release assets
        run: gh release download ${{ github.event.release.tag_name }} --dir dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          packages-dir: dist/
